name: "online_catalog"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ${DATA_PATH}/photos:/app/photos
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongodb
    networks:
      - catalog_network
    restart: unless-stopped
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}/mongo_data:/data/db
    networks:
      - catalog_network
    restart: unless-stopped

networks:
  catalog_network:
    driver: bridge
