name: "online_catalog"

services:

  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./frontend
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - catalog_network
    restart: unless-stopped


  frontend-prod:
    profiles: ["prod"]
    build:
      context: ./frontend
      target: production
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - catalog_network
    restart: unless-stopped



  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ${DATA_PATH}/photos:/app/photos
    environment:
      - MONGO_URL=${MONGO_URL}
      - DATA_PATH=${DATA_PATH}
      - ORIGIN=${ORIGIN}
    depends_on:
      - mongodb
    networks:
      - catalog_network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}/mongo_data:/data/db
    networks:
      - catalog_network
    restart: unless-stopped

networks:
  catalog_network:
    driver: bridge
